export const SEQUELIZE = 'SEQUELIZE';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const TASKS_REPOSITORY = 'TASKS_REPOSITORY';

export const jwtConstants = {
  secret: 'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};
